from datetime import date, timedelta
import random

from flask import Blueprint, jsonify, request, current_app

from models import (
    db, Organization, SecuritySignal, RiskAssessment,
    FinancialExposure, Policy, Coverage, RiskAlert,
    AnalystReview, ReviewHistory,
)
from services.risk_engine import calculate_risk_score, explain_change
from services.exposure_engine import estimate_exposure
from services.gap_engine import detect_gaps
from services.alert_engine import should_raise_alert, build_alert_payload

api = Blueprint("api", __name__, url_prefix="/api")


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------
def _signal_to_score_input(signal: SecuritySignal) -> dict:
    return {
        "critical_vulnerabilities": signal.critical_vulnerabilities,
        "mfa_coverage_pct": float(signal.mfa_coverage_pct),
        "security_incidents": signal.security_incidents,
        "backup_compliance_pct": float(signal.backup_compliance_pct),
        "patch_compliance_pct": float(signal.patch_compliance_pct),
    }


def _latest_two_assessments(org_id):
    assessments = (
        RiskAssessment.query.filter_by(org_id=org_id)
        .order_by(RiskAssessment.assessment_date.desc())
        .limit(2)
        .all()
    )
    return assessments  # [current, previous] or [current] or []


def run_assessment_pipeline(org: Organization, signal: SecuritySignal):
    """
    Core orchestration: Signal -> Risk Score -> Explanation -> Exposure ->
    Gap Analysis -> (maybe) Alert. Used both by seeding and by the
    'simulate next snapshot' endpoint. Returns the created RiskAssessment.
    """
    score_input = _signal_to_score_input(signal)
    result = calculate_risk_score(score_input)

    assessment = RiskAssessment(
        org_id=org.org_id,
        signal_id=signal.signal_id,
        assessment_date=signal.snapshot_date,
        risk_score=result["risk_score"],
        risk_band=result["risk_band"],
        score_breakdown=result["breakdown"],
    )
    db.session.add(assessment)
    db.session.flush()  # get assessment_id without full commit

    # Find previous assessment (before this one) for explanation + alerting
    previous = (
        RiskAssessment.query.filter(
            RiskAssessment.org_id == org.org_id,
            RiskAssessment.assessment_date < signal.snapshot_date,
        )
        .order_by(RiskAssessment.assessment_date.desc())
        .first()
    )
    previous_score_dict = (
        {"risk_score": float(previous.risk_score), "breakdown": previous.score_breakdown}
        if previous else None
    )
    current_score_dict = {"risk_score": result["risk_score"], "breakdown": result["breakdown"], "risk_band": result["risk_band"]}
    explanation = explain_change(previous_score_dict, current_score_dict)

    # Financial exposure
    exposure_vals = estimate_exposure(org.to_dict(), score_input, result["risk_score"])
    exposure = FinancialExposure(
        org_id=org.org_id,
        assessment_id=assessment.assessment_id,
        ransomware_exposure=exposure_vals["ransomware_exposure"],
        data_breach_exposure=exposure_vals["data_breach_exposure"],
        business_interruption_exposure=exposure_vals["business_interruption_exposure"],
        incident_response_exposure=exposure_vals["incident_response_exposure"],
        regulatory_legal_exposure=exposure_vals["regulatory_legal_exposure"],
    )
    db.session.add(exposure)
    db.session.flush()

    # Coverage gap analysis (uses the org's active policy, if any)
    policy = Policy.query.filter_by(org_id=org.org_id, status="Active").first()
    coverage_list = [c.to_dict() for c in policy.coverages] if policy else []
    gaps = detect_gaps(exposure_vals, coverage_list)

    delta = explanation["delta"]
    if should_raise_alert(delta, gaps, current_app.config["RISK_INCREASE_ALERT_THRESHOLD"]):
        payload = build_alert_payload(explanation, gaps)
        alert = RiskAlert(
            org_id=org.org_id,
            assessment_id=assessment.assessment_id,
            exposure_id=exposure.exposure_id,
            previous_score=payload["previous_score"],
            current_score=payload["current_score"],
            main_reason=payload["main_reason"],
            coverage_gap_summary=payload["coverage_gap_summary"],
            recommendation=payload["recommendation"],
            status=payload["status"],
        )
        db.session.add(alert)
        db.session.flush()
        db.session.add(ReviewHistory(
            alert_id=alert.alert_id,
            action="Alert Generated",
            notes="Automatically generated by risk pipeline. Pending analyst review.",
        ))

    db.session.commit()
    return assessment


# ---------------------------------------------------------------------
# Organizations
# ---------------------------------------------------------------------
@api.route("/organizations", methods=["GET"])
def list_organizations():
    orgs = Organization.query.all()
    return jsonify([o.to_dict() for o in orgs])


@api.route("/organizations/<int:org_id>", methods=["GET"])
def get_organization(org_id):
    org = Organization.query.get_or_404(org_id)
    return jsonify(org.to_dict())


# ---------------------------------------------------------------------
# Security Signals
# ---------------------------------------------------------------------
@api.route("/organizations/<int:org_id>/signals", methods=["GET"])
def get_signals(org_id):
    signals = (
        SecuritySignal.query.filter_by(org_id=org_id)
        .order_by(SecuritySignal.snapshot_date.asc())
        .all()
    )
    return jsonify([s.to_dict() for s in signals])


# ---------------------------------------------------------------------
# Risk Assessments
# ---------------------------------------------------------------------
@api.route("/organizations/<int:org_id>/assessments", methods=["GET"])
def get_assessments(org_id):
    assessments = (
        RiskAssessment.query.filter_by(org_id=org_id)
        .order_by(RiskAssessment.assessment_date.asc())
        .all()
    )
    return jsonify([a.to_dict() for a in assessments])


@api.route("/organizations/<int:org_id>/latest-assessment", methods=["GET"])
def get_latest_assessment(org_id):
    assessments = _latest_two_assessments(org_id)
    if not assessments:
        return jsonify({"error": "No assessments yet for this organization"}), 404

    current = assessments[0]
    previous = assessments[1] if len(assessments) > 1 else None

    current_dict = {
        "risk_score": float(current.risk_score),
        "breakdown": current.score_breakdown,
        "risk_band": current.risk_band,
    }
    previous_dict = (
        {"risk_score": float(previous.risk_score), "breakdown": previous.score_breakdown}
        if previous else None
    )
    explanation = explain_change(previous_dict, current_dict)

    return jsonify({
        "assessment": current.to_dict(),
        "explanation": explanation,
    })


# ---------------------------------------------------------------------
# Financial Exposure & Coverage Gaps
# ---------------------------------------------------------------------
@api.route("/organizations/<int:org_id>/exposure", methods=["GET"])
def get_exposure(org_id):
    exposure = (
        FinancialExposure.query.filter_by(org_id=org_id)
        .order_by(FinancialExposure.created_at.desc())
        .first()
    )
    if not exposure:
        return jsonify({"error": "No exposure data yet"}), 404
    return jsonify(exposure.to_dict())


@api.route("/organizations/<int:org_id>/coverage-gaps", methods=["GET"])
def get_coverage_gaps(org_id):
    exposure = (
        FinancialExposure.query.filter_by(org_id=org_id)
        .order_by(FinancialExposure.created_at.desc())
        .first()
    )
    if not exposure:
        return jsonify({"error": "No exposure data yet"}), 404

    policy = Policy.query.filter_by(org_id=org_id, status="Active").first()
    coverage_list = [c.to_dict() for c in policy.coverages] if policy else []
    gaps = detect_gaps(exposure.to_dict(), coverage_list)
    return jsonify({
        "policy": policy.to_dict() if policy else None,
        "gaps": gaps,
    })


# ---------------------------------------------------------------------
# Alerts
# ---------------------------------------------------------------------
@api.route("/alerts", methods=["GET"])
def list_alerts():
    status = request.args.get("status")
    query = RiskAlert.query
    if status:
        query = query.filter_by(status=status)
    alerts = query.order_by(RiskAlert.created_at.desc()).all()
    return jsonify([a.to_dict() for a in alerts])


@api.route("/alerts/<int:alert_id>", methods=["GET"])
def get_alert(alert_id):
    alert = RiskAlert.query.get_or_404(alert_id)
    return jsonify(alert.to_dict())


@api.route("/alerts/<int:alert_id>/history", methods=["GET"])
def get_alert_history(alert_id):
    history = (
        ReviewHistory.query.filter_by(alert_id=alert_id)
        .order_by(ReviewHistory.action_at.asc())
        .all()
    )
    reviews = (
        AnalystReview.query.filter_by(alert_id=alert_id)
        .order_by(AnalystReview.reviewed_at.asc())
        .all()
    )
    return jsonify({
        "history": [h.to_dict() for h in history],
        "reviews": [r.to_dict() for r in reviews],
    })


@api.route("/alerts/<int:alert_id>/review", methods=["POST"])
def review_alert(alert_id):
    """
    Human-in-the-loop decision endpoint. This is the ONLY way an alert's
    status changes. The system itself never auto-approves or auto-rejects.
    """
    alert = RiskAlert.query.get_or_404(alert_id)
    data = request.get_json(force=True) or {}

    analyst_name = data.get("analyst_name", "").strip()
    decision = data.get("decision")
    comments = data.get("comments", "")

    if not analyst_name:
        return jsonify({"error": "analyst_name is required"}), 400
    if decision not in ("Approve", "Reject", "Request Info"):
        return jsonify({"error": "decision must be Approve, Reject, or Request Info"}), 400

    review = AnalystReview(
        alert_id=alert_id,
        analyst_name=analyst_name,
        decision=decision,
        comments=comments,
    )
    db.session.add(review)

    status_map = {
        "Approve": "Approved",
        "Reject": "Rejected",
        "Request Info": "Info Requested",
    }
    alert.status = status_map[decision]

    db.session.add(ReviewHistory(
        alert_id=alert_id,
        action=f"Analyst decision: {decision}",
        notes=comments or "(no comments provided)",
    ))
    db.session.commit()

    return jsonify({
        "alert": alert.to_dict(),
        "review": review.to_dict(),
    })


# ---------------------------------------------------------------------
# Dashboard aggregate
# ---------------------------------------------------------------------
@api.route("/dashboard/<int:org_id>", methods=["GET"])
def dashboard(org_id):
    org = Organization.query.get_or_404(org_id)

    assessments = (
        RiskAssessment.query.filter_by(org_id=org_id)
        .order_by(RiskAssessment.assessment_date.asc())
        .all()
    )
    if not assessments:
        return jsonify({"error": "No assessments yet for this organization"}), 404

    current = assessments[-1]
    previous = assessments[-2] if len(assessments) > 1 else None

    current_dict = {"risk_score": float(current.risk_score), "breakdown": current.score_breakdown, "risk_band": current.risk_band}
    previous_dict = (
        {"risk_score": float(previous.risk_score), "breakdown": previous.score_breakdown}
        if previous else None
    )
    explanation = explain_change(previous_dict, current_dict)

    latest_signal = SecuritySignal.query.get(current.signal_id)
    exposure = (
        FinancialExposure.query.filter_by(assessment_id=current.assessment_id).first()
    )
    policy = Policy.query.filter_by(org_id=org_id, status="Active").first()
    coverage_list = [c.to_dict() for c in policy.coverages] if policy else []
    gaps = detect_gaps(exposure.to_dict(), coverage_list) if exposure else []

    alerts = RiskAlert.query.filter_by(org_id=org_id).order_by(RiskAlert.created_at.desc()).all()
    pending = [a for a in alerts if a.status == "Pending Analyst Review"]

    return jsonify({
        "organization": org.to_dict(),
        "trend": [{"date": a.assessment_date.isoformat(), "score": float(a.risk_score), "band": a.risk_band} for a in assessments],
        "current_assessment": current.to_dict(),
        "explanation": explanation,
        "latest_signal": latest_signal.to_dict() if latest_signal else None,
        "exposure": exposure.to_dict() if exposure else None,
        "policy": policy.to_dict() if policy else None,
        "coverage_gaps": gaps,
        "alerts": [a.to_dict() for a in alerts],
        "pending_review_count": len(pending),
        "disclaimer": current_app.config["DATA_DISCLAIMER"],
    })


# ---------------------------------------------------------------------
# Simulate a new signal snapshot (demo / what-if button)
# ---------------------------------------------------------------------
@api.route("/simulate/<int:org_id>", methods=["POST"])
def simulate_next_snapshot(org_id):
    """
    Generates a new, randomly-perturbed simulated signal snapshot for the
    organization based on its most recent one, then runs the full pipeline.
    This is a demo convenience -- in a real deployment this endpoint would
    be replaced by an ingestion feed of actual (simulated-in-this-project)
    telemetry connectors.
    """
    org = Organization.query.get_or_404(org_id)
    last_signal = (
        SecuritySignal.query.filter_by(org_id=org_id)
        .order_by(SecuritySignal.snapshot_date.desc())
        .first()
    )
    if not last_signal:
        return jsonify({"error": "No baseline signal to simulate from"}), 400

    scenario = request.get_json(silent=True) or {}
    direction = scenario.get("direction", "random")  # "worsen" | "improve" | "random"

    def drift(value, low, high, worsen_delta, improve_delta):
        if direction == "worsen":
            delta = worsen_delta
        elif direction == "improve":
            delta = improve_delta
        else:
            delta = random.choice([worsen_delta, improve_delta, 0])
        return max(low, min(high, value + delta))

    new_signal = SecuritySignal(
        org_id=org_id,
        snapshot_date=last_signal.snapshot_date + timedelta(days=30),
        critical_vulnerabilities=int(drift(last_signal.critical_vulnerabilities, 0, 25, random.randint(1, 4), -random.randint(0, 2))),
        patch_compliance_pct=drift(float(last_signal.patch_compliance_pct), 0, 100, -random.uniform(3, 10), random.uniform(1, 5)),
        mfa_coverage_pct=drift(float(last_signal.mfa_coverage_pct), 0, 100, -random.uniform(5, 15), random.uniform(1, 5)),
        security_incidents=int(drift(last_signal.security_incidents, 0, 20, random.randint(0, 2), -min(last_signal.security_incidents, random.randint(0, 1)))),
        backup_compliance_pct=drift(float(last_signal.backup_compliance_pct), 0, 100, -random.uniform(2, 10), random.uniform(1, 4)),
        endpoint_protection_pct=drift(float(last_signal.endpoint_protection_pct), 0, 100, -random.uniform(1, 5), random.uniform(1, 3)),
        training_compliance_pct=drift(float(last_signal.training_compliance_pct), 0, 100, -random.uniform(2, 8), random.uniform(1, 4)),
        avg_remediation_days=max(0, float(last_signal.avg_remediation_days) + (random.uniform(0.5, 3) if direction != "improve" else -random.uniform(0.2, 1.5))),
    )
    db.session.add(new_signal)
    db.session.flush()

    assessment = run_assessment_pipeline(org, new_signal)

    return jsonify({
        "signal": new_signal.to_dict(),
        "assessment": assessment.to_dict(),
    }), 201
